#!/bin/sh

help="usage:  anistart <operation>
operations:
    anistart {-s --start}
    anistart {-S --stop}
    anistart {-h --help}"

start()
{
	echo "Mounting rclone"
	ping -qc1 8.8.8.8 > /dev/null 2>&1 \
		&& rclone mount --daemon --allow-other jousd-drive: /media/drive/jousd-drive-root \
		&& rclone mount --daemon --allow-other jousd-drive-timing: /media/drive/jousd-drive-timing\
		&& rclone mount --daemon --allow-other jousd-drive-subeki: /media/drive/jousd-drive-subeki \
		|| echo "Error: no internet" 
}

stop()
{
	echo "Unmounting rclone"
	[ -n "$(pgrep rclone)" ] \
		&& sudo fusermount -u /media/drive/jousd-drive-root \
		&& sudo fusermount -u /media/drive/jousd-drive-timing\
		&& sudo fusermount -u /media/drive/jousd-drive-subeki
}

case $1 in 
-s | --start)
	start
	;;
-S | --stop)
	stop
	;;
-h | --help)
	printf "%s\n" "$help"
	;;
*)
	printf "anistart: invalid option -- '%s'\n" "$1"
	;;
esac


