#!/bin/sh

start ()
{
	echo "Changing /var/lib/transmission group"
	sudo chgrp -R supahx /var/lib/transmisson

	echo "Mounting rclone"
	ping -qc1 8.8.8.8 > /dev/null 2>&1 \
		&& rclone mount --daemon jousd-drive: /media/drive/jousd-drive-root \
		&& rclone mount --daemon jousd-drive-crypt: /media/drive/jousd-drive-crypt \
		|| echo "Error: no internet" 
}

stop ()
{
	echo "Unmounting rclone"
	[ -n "$(pgrep rclone)" ] \
		&& sudo fusermount -u /media/drive/jousd-drive-root \
		&& sudo fusermount -u /media/drive/jousd-drive-crypt 
}

case $1 in 
-s | --start)
	start
	;;
-S | --stop)
	stop
	;;
-h | --help)
	printf "anistart usage: anistart <option>\noptions:\n"
	;;
*)
	printf "anistart: option '%s' not found\nUse '-h' for options\n" "$1"
	;;
esac


