#!/bin/bash

transmission-remote -l | while IFS="" read -r p || [ -n "$p" ] 
do
	RATIO="$(printf '%s\n' "$p" | cut -b 53-53)"

	if [ "$RATIO" -ge "1" ]
	then
		ID="$(echo "$p" | awk '{print $1}')"
		NAME="$(printf '%s\n' "$p" | cut -b 71-)"
		echo "uploading and removing $NAME ..."
		transmission-remote -t "$ID" -r
		rclone copy /var/lib/transmission-daemon/downloads/"$NAME" jousd-drive:"$NAME"
		sudo rm -r /var/lib/transmission-daemon/downloads/"$NAME"
	fi
done
