#!/bin/bash

transmission-remote -l | while IFS="" read -r p || [ -n "$p" ]
do
	DONE="$(echo "$p" | awk '{print $2}')"
	if [ "$DONE" = "100%" ]
	then
		ID="$(echo "$p" | cut -b -4)"
		NAME="$(transmission-remote -t$ID -i | grep Name: | cut -b 9-)"
		echo "Uploading/checking $NAME"
	        rclone copy -P /var/lib/transmission-daemon/downloads/"$NAME" jousd-drive:"$NAME" 
	fi	
done

