#!/bin/bash

transmission-remote -l | while IFS="" read -r p || [ -n "$p" ]
do
	ID="$(echo "$p" | awk '{print $1}')"
	if [ "$1" -eq "$ID" ]
	then
		NAME="$(printf '%s\n' "$p" | cut -b 71-)"
		echo "Uploading and removing $NAME ..."
		transmission-remote -t "$ID" -r
	        rclone copy /var/lib/transmission-daemon/downloads/"$NAME" jousd-drive:"$NAME"
	        sudo rm -r /var/lib/transmission-daemon/downloads/"$NAME"	
	fi	
done

