#!/bin/bash

transmission-remote -l | while IFS="" read -r p || [ -n "$p" ]
do
	DONE="$(echo "$p" | awk '{print $2}')"
	if [ "$DONE" = "100%" ]
	then
		NAME="$(printf '%s\n' "$p" | cut -b 71-)"
	        rclone copy /var/lib/transmission-daemon/downloads/"$NAME" jousd-drive:"$NAME" 
	fi	
done

