#!/bin/sh

start()
{
	echo "initializing rfkill"
	sudo rfkill unblock 0
	sudo rfkill unblock 1 && echo done

	echo "initializing wpa_supplicant"
	sudo killall wpa_supplicant 
	sudo wpa_supplicant -B -i wlp1s0 -c /etc/wpa_supplicant/wpa_supplicant.conf
	sudo wpa_cli enable_network 0 && echo done

	echo initializing dhcpcd
	sudo dhcpcd && echo done
}

case $1 in
-s | --start)
	start
	;;
esac
