#!/bin/sh

curl $1 | grep "File:" | cut -d '"' -f 8 | sed 's/^/https:\/\/jojowiki.com/' > filepages

cat filepages | while read -r p
        do
                IMAGEURL=$( curl -s "$p" | grep og:image | cut -d \" -f 4 )
                wget -q "$IMAGEURL"
        done

echo "Finished downloading $(find . -name '*' -exec file {} \; | grep -o -P '^.+: \w+ image' | wc -l ) images"
