#!/bin/bash

mkdir -p ~/.nyaa_rss
cd ~/.nyaa_rss

# Get RSS feeds and store them in ~/.nyaa_rss/

cat ~/.releases | while IFS="" read -r p || [ -n "$p" ]
do
	wget -q -N $p
done

# Get latest torrent from RSS feeds and add to transmission
for FILE in *
do
	LINK="$(grep ".torrent" $FILE | head -n 1 | awk -v RS='<[^>]+>' -v ORS= '1')"
	transmission-remote -a $LINK
done

cd - > /dev/null

