#!/bin/sh

REMOTE=$1
RCLONE_CONFIG_PASS="$(pass rclone/config)"
export RCLONE_CONFIG_PASS

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No color (terminate color)

transmission-remote -l | grep 100% | while IFS="" read -r COMPLETED || [ -n "$COMPLETED" ]
do
	ID=$(echo $COMPLETED | cut -d ' ' -f 1)
	NAME=$(transmission-remote -t $ID -i | grep Name: | cut -b 9-)
	DIR=$(transmission-remote -t $ID -i | grep Location: | cut -b 13-)
	REMOTE_PATH=$(echo $DIR | sed -n 's/\/var\/lib\/transmission\/downloads\///p')
	printf "Uploading ${RED}$DIR/$NAME${NC} to ${YELLOW}$REMOTE$REMOTE_PATH${NC}...\n"
	rclone copy --progress "$DIR/$NAME" $REMOTE$REMOTE_PATH
done

# Example usage:
# ./completed jousd-drive-neocrypt:

