#!/bin/sh

ID=$1
REMOTE=$2
RCLONE_CONFIG_PASS="$(pass rclone/config)"
export RCLONE_CONFIG_PASS

RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No color (terminate color)

NAME=$(transmission-remote -t $ID -i | grep Name: | cut -b 9-)
DIR=$(transmission-remote -t $ID -i | grep Location: | cut -b 13-)
REMOTE_PATH=$(echo $DIR | sed -n 's/\/var\/lib\/transmission\/downloads\///p')
printf "Uploading ${RED}$NAME${NC} to ${YELLOW}$REMOTE$REMOTE_PATH${NC}...\n"
rclone copyto -Pv "$DIR/$NAME" "$REMOTE$REMOTE_PATH$NAME"
printf "${RED}REMOVING $NAME\n"
transmission-remote -t $ID -rad

# Example usage:
# ./remove 12 jousd-drive-neocrypt:

