#!/bin/bash 

transmission-remote -l | while IFS="" read -r p || [ -n "$p" ]
do
	ID="$(echo "$p" | awk '{print $1}')"
	NAME="$(transmission-remote -t $ID -i | grep Name: | cut -b 9-)"
	RATIO="$(transmission-remote -t $ID -i | grep Ratio: | awk '{print $2}' | cut -b -1)"

	if [ "$NAME" != "" ]
	then 
		if [ $RATIO -ge 1 ]
		then
			echo $NAME
			echo "Uploading and removing $NAME"
			echo "rclone copy /var/lib/transmission-daemon/downloads/$NAME jousd-drive:$NAME"
			echo "transmission-remote -t $ID -rad"
		fi
	fi
done

